{% set name = "nlptest" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nlptest-{{ version }}.tar.gz
  sha256: 4d56528a2af3bbc335a98f81b105e21d8cfada220939efbe2d43ac8abae26b7a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<3.12
    - pip
  run:
    - python >=3.7,<3.12
    - numpy
    - pandas
    - wn
    - scikit-learn
    - transformers
    - nltk
    - pytorch
    - sentencepiece
    - pydantic

test:
  imports:
    - nlptest
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.nlptest.org
  summary: John Snow Labs provides a library for delivering safe & effective NLP models.
  license: Apache-2.0
  license_file: LICENSE
  description: |
    `nlptest` is an open-source Python library designed to help developers
    deliver safe and effective Natural Language Processing (NLP) models.

    PyPI: [https://pypi.org/project/nlptest/](https://pypi.org/project/nlptest/)

  dev_url: https://github.com/JohnSnowLabs/nlptest/
  doc_url: https://nlptest.org/docs/pages/docs/install

extra:
  recipe-maintainers:
    - sugatoray
